@startuml ドメインモデル


object 救急隊
object ロストトラッカー
object 位置情報
object システム管理者
object 利用者
object マップ
object スキー
object 旅行
object ツアー旅行
object メモ
object ツアー情報
object 連絡
object 機能
object グループ
object チャット
object 通知


システム管理者 -- 救急隊 : 通報
システム管理者 o-- ロストトラッカー
ロストトラッカー o-- 利用者

ロストトラッカー o-- 機能
機能 <|-- 連絡
連絡 o-- チャット
連絡 o-- 通知

機能 <|-- マップ
マップ o-- 位置情報

機能 <|-- グループ
機能 <|-- ツアー情報

ツアー情報 o-- スキー
ツアー情報 o-- 旅行
ツアー情報 o-- ツアー旅行
ツアー情報 o-- メモ

@enduml

@startuml ドメインモデル2

object 救急隊
object ロストトラッカー
object システム管理者
object ユーザー
object パートナー企業

object 位置情報
object マップ
object スキー
object 旅行
object ツアー旅行

object ツアー情報
object 連絡
object グループ
object チャット
object 緊急通知

object 新規登録
object ログイン
object ログアウト
object 集合ルート


システム管理者 -- 救急隊 : 通報
パートナー企業 o-- ロストトラッカー
システム管理者 o-- ロストトラッカー
ロストトラッカー o-- ユーザー

ユーザー o-- 連絡
連絡 o-- チャット
連絡 o-- 緊急通知

ユーザー o-- 新規登録
ユーザー o-- ログイン
ユーザー o-- ログアウト

ユーザー o-- グループ

ロストトラッカー o-- マップ
マップ o-- 集合ルート
マップ o-- 位置情報
ロストトラッカー o-- ツアー情報

ツアー情報 o-- スキー
ツアー情報 o-- 旅行
ツアー情報 o-- ツアー旅行

@enduml


@startuml ドメインモデル３

object 救急隊
object ロストトラッカー
object システム管理者
object ユーザー
object パートナー企業

object 位置情報
object マップ

object ツアー情報
object 連絡
object グループ
object チャット
object 緊急通知

object 新規登録
object ログイン
object ログアウト
object 集合ルート
object 移動履歴


システム管理者 -- 救急隊 : 通報
パートナー企業 o-- ロストトラッカー
システム管理者 o-- ロストトラッカー
ロストトラッカー o-- ユーザー

ユーザー o-- 連絡
連絡 o-- チャット
連絡 o-- 緊急通知

ユーザー o-- 新規登録
ユーザー o-- ログイン
ユーザー o-- ログアウト

ユーザー o-- グループ

ロストトラッカー o-- マップ
マップ o-- 集合ルート
マップ o-- 位置情報
マップ o-- 移動履歴


ロストトラッカー o-- ツアー情報

@enduml


@startuml ドメインモデル4

object 救急隊
object ロストトラッカー
object システム管理者
object ユーザー
object パートナー企業

object 位置情報
object マップ

object ツアー情報
object 連絡
object グループ
object チャット
object 緊急通知

object 新規登録
object ログイン
object ログアウト
object 集合ルート
object 移動履歴



システム管理者 -- 救急隊 : 通報
システム管理者 o-- パートナー企業
パートナー企業 o-- ロストトラッカー
システム管理者 o-- ロストトラッカー
ロストトラッカー o-- ユーザー

ユーザー o-- 連絡
連絡 o-- チャット
連絡 o-- 緊急通知

ユーザー o-- 新規登録
ユーザー o-- ログイン
ユーザー o-- ログアウト

ユーザー o-- グループ

ロストトラッカー o-- マップ
マップ o-- 集合ルート
マップ o-- 位置情報
マップ o-- 移動履歴


ロストトラッカー o-- ツアー情報

@enduml