@startuml システム管理者_usecase
left to right direction
actor システム管理者

システム管理者 -- (システム管理者がログインする)
システム管理者 -- (システム管理者がログアウトする)
システム管理者 -- (パスワード変更)
システム管理者 -- (ユーザーの登録情報を確認する)
システム管理者 -- (ユーザーの異常を確認する)
システム管理者 -- (ユーザーの情報を削除する)
システム管理者 -- (ユーザーとチャットする)




@enduml