@startuml user_usecase11/30

left to right direction
actor ユーザー

ユーザー -- (ユーザーを新規登録する)
ユーザー -- (ユーザーがログインする)
ユーザー -- (ユーザーがログアウトする)
ユーザー -- (登録情報を変更する)
ユーザー -- (システムから退会する)
(登録情報を変更する) ..> (登録情報を確認する) : <<include>>
(システムから退会する) ..> (登録情報を確認する) : <<include>>
ユーザー -- (イベントに参加する)
ユーザー -- (イベントを退出する)
ユーザー -- (グループを作成する)
ユーザー -- (グループに参加する)
ユーザー -- (グループを退出する)
ユーザー -- (自身の状況を変更する)
ユーザー -- (位置情報を表示する)
ユーザー -- (ルートを表示する)
ユーザー -- (システム管理者とチャットする)
ユーザー -- (パスワード変更)


@enduml
