@startuml パートナー企業_usecase11/30
left to right direction
actor パートナー企業

パートナー企業 -- (パートナー企業が新規登録する)
パートナー企業 -- (パートナー企業がログインする)
パートナー企業 -- (パートナー企業がログアウトする)
パートナー企業 -- (ツアー参加者の登録情報を確認する)
パートナー企業 -- (パスワードを変更する)
パートナー企業 -- (イベントを作成する)
パートナー企業 -- (イベントを変更する)
パートナー企業 -- (イベントを削除する)
パートナー企業 -- (ユーザーとチャットする)
パートナー企業 -- (ユーザーの異常を確認する)
@enduml